services:
  cache:
    container_name: redis_2_cache
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ShopNetwork

  backend:
    build:
      context: .
    container_name: backend_2_cache
    ports:
      - "8000:8000"
    networks:
      - ShopNetwork
    command:
      - /app/start.sh

  notifications_worker:
    build:
      context: .
    container_name: notifications_worker_2_cache
    networks:
      - ShopNetwork
    command: ["python", "src/notifications/subscriber.py"]

volumes:
  redis_data:

networks:
  ShopNetwork:
    external: true
