"""add_product_sub_table

Revision ID: 2938b3e4c563
Revises: 297989a01ddf
Create Date: 2026-09-24 15:24:52.870009

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2938b3e4c563"
down_revision: str | Sequence[str] | None = "297989a01ddf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_subs",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("product_id", "user_id", name=op.f("pk_product_subs")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_subs")
    # ### end Alembic commands ###
