"""add_invoked_at_field

Revision ID: 6d0e4a270d4d
Revises: c9e2b61e7144
Create Date: 2026-09-23 08:17:14.351685

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6d0e4a270d4d"
down_revision: str | Sequence[str] | None = "c9e2b61e7144"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_tokens",
        sa.Column("invoked_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_tokens", "invoked_at")
    # ### end Alembic commands ###
