"""add_user_id_to_notifications

Revision ID: a094880f3c31
Revises: 8be774ed5d76
Create Date: 2026-09-24 20:50:27.547387

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a094880f3c31"
down_revision: str | Sequence[str] | None = "8be774ed5d76"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="Пользователь, который должен получить это уведомление",
        ),
    )
    op.create_foreign_key(
        op.f("fk_notifications_user_id_users"),
        "notifications",
        "users",
        ["user_id"],
        ["user_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_notifications_user_id_users"),
        "notifications",
        type_="foreignkey",
    )
    op.drop_column("notifications", "user_id")
    # ### end Alembic commands ###
